"""v2 postgres safe schema expansion

Revision ID: 60890b0d6a4b
Revises: 6341db2af759
Create Date: 2026-04-26 15:15:30.556895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60890b0d6a4b'
down_revision = '6341db2af759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('scopes_json', sa.JSON(), nullable=True),
    sa.Column('monthly_lookup_limit', sa.Integer(), nullable=True),
    sa.Column('lookup_credits', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('api_lookup_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_lookup_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_lookup_event_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_lookup_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_lookup_event_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('accessibility_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toilet_distance_from_bar_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verified_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accessibility_profile_verified_by_user_id'), ['verified_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_accessibility_profile_verified_by_user_id_user', 'user', ['verified_by_user_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False))
        batch_op.add_column(sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('moderation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comment_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_comment_reviewed_by_user_id_user', 'user', ['reviewed_by_user_id'], ['id'])

    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    with op.batch_alter_table('search_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filters_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('result_count', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index('ix_search_event_user_created_at', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=50), server_default=sa.text("'free'"), nullable=False))
        batch_op.add_column(sa.Column('monthly_search_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('search_credits', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('community_points', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('rank_title', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('age_verification_status', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('age_verification_status')
        batch_op.drop_column('rank_title')
        batch_op.drop_column('community_points')
        batch_op.drop_column('search_credits')
        batch_op.drop_column('monthly_search_limit')
        batch_op.drop_column('plan')

    with op.batch_alter_table('search_event', schema=None) as batch_op:
        batch_op.drop_index('ix_search_event_user_created_at')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('result_count')
        batch_op.drop_column('filters_json')

    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_reviewed_by_user_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comment_status'))
        batch_op.drop_index(batch_op.f('ix_comment_reviewed_by_user_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('moderation_reason')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_user_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('accessibility_profile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accessibility_profile_verified_by_user_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accessibility_profile_verified_by_user_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('verified_by_user_id')
        batch_op.drop_column('toilet_distance_from_bar_m')

    with op.batch_alter_table('api_lookup_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_lookup_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_lookup_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_api_lookup_event_api_key_id'))

    op.drop_table('api_lookup_event')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_key_is_active'))
        batch_op.drop_index(batch_op.f('ix_api_key_created_at'))

    op.drop_table('api_key')
    # ### end Alembic commands ###
