"""initial postgres schema

Revision ID: 6341db2af759
Revises: 
Create Date: 2026-04-26 15:07:23.736618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6341db2af759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('venue_type', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('town', sa.String(length=120), nullable=True),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_postcode'), ['postcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_place_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_town'), ['town'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('accessibility_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('toilets_available', sa.String(length=30), nullable=True),
    sa.Column('toilet_location', sa.String(length=120), nullable=True),
    sa.Column('toilet_distance_from_bar', sa.String(length=120), nullable=True),
    sa.Column('accessible_toilet', sa.String(length=30), nullable=True),
    sa.Column('baby_changing', sa.String(length=30), nullable=True),
    sa.Column('baby_changing_location', sa.String(length=120), nullable=True),
    sa.Column('step_free_entrance', sa.String(length=30), nullable=True),
    sa.Column('stairs_inside', sa.String(length=30), nullable=True),
    sa.Column('lift_available', sa.String(length=30), nullable=True),
    sa.Column('disabled_parking', sa.String(length=30), nullable=True),
    sa.Column('sensory_notes', sa.Text(), nullable=True),
    sa.Column('public_comments', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_table('call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=80), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_log_created_at'), ['created_at'], unique=False)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_created_at'), ['created_at'], unique=False)

    op.create_table('search_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(length=255), nullable=True),
    sa.Column('town', sa.String(length=120), nullable=True),
    sa.Column('accessible', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_event_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_event_created_at'))

    op.drop_table('search_event')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_created_at'))

    op.drop_table('comment')
    with op.batch_alter_table('call_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_log_created_at'))

    op.drop_table('call_log')
    op.drop_table('accessibility_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_place_town'))
        batch_op.drop_index(batch_op.f('ix_place_status'))
        batch_op.drop_index(batch_op.f('ix_place_slug'))
        batch_op.drop_index(batch_op.f('ix_place_postcode'))
        batch_op.drop_index(batch_op.f('ix_place_name'))
        batch_op.drop_index(batch_op.f('ix_place_county'))

    op.drop_table('place')
    # ### end Alembic commands ###
